#!/usr/bin/python

import datetime
import os
import sys
import time

DIR = os.path.abspath(os.path.dirname(__file__))

CACHE_DIR = os.path.join(DIR, "cache")

def main(args):
    thresh = time.mktime((datetime.datetime.now() - datetime.timedelta(weeks=4)).timetuple())

    for root, dirs, files in os.walk(CACHE_DIR):
        for f in files:
            path = os.path.join(root, f)
            if '.' in f or os.stat(path).st_atime < thresh:
                os.unlink(path)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
